Repository alissatroiano/team-4-april-2022, pull requests merged in 2022-04, with the labels that each got.

#6 initial commit
  README.md
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: documentation

#11 add Layout to README
  README.md
Labels: documentation

#13 added bootstrap to the html
  index.html
Labels: documentation

#28 add database sources and first schema to README.md
  README.md
  docs/readme_img/firstDBschema.png
Labels: documentation

#42 Alissa Landing Page
  assets/css/style.css
  assets/images/electric.png
  assets/images/electrillo.png
  assets/images/image.png
  assets/js/create-nav-and-footer.js
  assets/js/script.js
  index.html
  mission.html
  questions.html
Labels: enhancement

#40 image link correction on README.md
  README.md
Labels: documentation

#44 Nicks branch
  assets/js/fuel-saving-calculator.js
  questions.html
Labels: enhancement

#46 45 quetionshtml card display and js coming from the wrong file bug
  assets/js/fuel-saving-calculator.js
  questions.html
Labels: bug

#48 Fix JS Bug & Add Testing Documentation
  README.md
  TESTING.md
  assets/css/style.css
  assets/js/create-nav-and-footer.js
  assets/js/script.js
  index.html
  questions.html
Labels: bug

#56 Update questions page to ally with team strategy
  assets/css/style.css
  index.html
  questions.html
Labels: enhancement

#69 update readme with UX experience, features and images
  README.md
  docs/readme_img/color-scheme.png
  docs/readme_img/responsivePage.png
  docs/wireframes/Wireframe_1.png
  docs/wireframes/Wireframe_2.png
  docs/wireframes/Wireframe_3.png
  docs/wireframes/Wireframe_4.png
  docs/wireframes/wireframes.md
Labels: documentation

#74 UX and related images for README.md
  README.md
  docs/hackathon_tradeoff.pdf
  docs/readme_img/tradeoff.png
  docs/tradeoff.pdf
  docs/wireframes/firstWireframe.png
  docs/wireframes/wireframes.md
  docs/wireframes/wireframes.pdf
Labels: documentation

#76 Testing
  404.html
  README.md
  TESTING.md
  assets/css/style.css
  assets/js/script.js
  index.html
  team.html
Labels: documentation
